"""added is_completed to Order model

Revision ID: 5ccf31b35818
Revises: b7da71ae833a
Create Date: 2023-06-14 14:31:07.119751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ccf31b35818'
down_revision = 'b7da71ae833a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_constraint('table_ibfk_2', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('table_ibfk_2', 'order', ['order_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
